/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import dao.SE140364_TblItemDAO;
import dao.SE140364_TblSuppliersDAO;
import dto.SE140364_Item;
import dto.SE140364_Suppliers;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author Henry
 */
public class SE140364_ManagementUI extends javax.swing.JFrame {

    SE140364_TblItemDAO modelItem;
    SE140364_TblSuppliersDAO modelSuppliers;
    final int SUCCESS = 1;
    boolean addNewItem = true;
    boolean addNewSup = true;
    boolean deleteSup = true;
    boolean deleteItem = true;

    /**
     * Creates new form ManagementUI
     */
    public SE140364_ManagementUI() throws Exception {
        initComponents();

        modelSuppliers = new SE140364_TblSuppliersDAO();
        tblSuppliers.setModel(modelSuppliers.getModelSup());

        modelItem = new SE140364_TblItemDAO();
        tblItem.setModel(modelItem.getModeItem());

        try {
            CBSupplier.setModel(new DefaultComboBoxModel<>(modelSuppliers.getListSuppliersComboBox()));
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    void clearInformationItemOnTable() {
        txtCodeItem.setText("");
        txtNameItem.setText("");
        CBSupplier.setSelectedItem(null);
        txtUnit.setText("");
        txtPrice.setText("");
        CKsupplying.setSelected(false);
    }

    void clearInformationSupplierOnTable() {
        txtSupCode.setText("");
        txtSupName.setText("");
        txtAddressSup.setText("");
        CKsupplying.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbbSupplier = new javax.swing.JTabbedPane();
        pnSuplier = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSuppliers = new javax.swing.JTable();
        pnSuplierDetails = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        btnAddNewSup = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtSupCode = new javax.swing.JTextField();
        txtSupName = new javax.swing.JTextField();
        txtAddressSup = new javax.swing.JTextField();
        CKcoll = new javax.swing.JCheckBox();
        btnSaveSup = new javax.swing.JButton();
        btnDeleteSup = new javax.swing.JButton();
        pnItem = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblItem = new javax.swing.JTable();
        pnItemDetails = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btnAddNewItem = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtCodeItem = new javax.swing.JTextField();
        txtNameItem = new javax.swing.JTextField();
        txtUnit = new javax.swing.JTextField();
        CKsupplying = new javax.swing.JCheckBox();
        btnSaveItem = new javax.swing.JButton();
        btnDeleteItem = new javax.swing.JButton();
        txtPrice = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        CBSupplier = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblSuppliers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSuppliers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSuppliersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSuppliers);

        jLabel20.setText("Collaboration");

        btnAddNewSup.setText("Add New");
        btnAddNewSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewSupActionPerformed(evt);
            }
        });

        jLabel21.setText("Code");

        jLabel22.setText("Address");

        jLabel23.setText("Name");

        txtSupCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupCodeActionPerformed(evt);
            }
        });

        txtSupName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupNameActionPerformed(evt);
            }
        });

        txtAddressSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressSupActionPerformed(evt);
            }
        });

        btnSaveSup.setText("Save");
        btnSaveSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveSupActionPerformed(evt);
            }
        });

        btnDeleteSup.setText("Delete");
        btnDeleteSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnSuplierDetailsLayout = new javax.swing.GroupLayout(pnSuplierDetails);
        pnSuplierDetails.setLayout(pnSuplierDetailsLayout);
        pnSuplierDetailsLayout.setHorizontalGroup(
            pnSuplierDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSuplierDetailsLayout.createSequentialGroup()
                .addGroup(pnSuplierDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnSuplierDetailsLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(pnSuplierDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnSuplierDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnSuplierDetailsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAddNewSup, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnSuplierDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnSuplierDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtSupCode, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSupName, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAddressSup, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CKcoll)
                    .addGroup(pnSuplierDetailsLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnSaveSup, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(btnDeleteSup, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnSuplierDetailsLayout.setVerticalGroup(
            pnSuplierDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSuplierDetailsLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(pnSuplierDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSupCode, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnSuplierDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSupName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnSuplierDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddressSup, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnSuplierDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CKcoll))
                .addGap(51, 51, 51)
                .addGroup(pnSuplierDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddNewSup, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSaveSup, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteSup, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnSuplierLayout = new javax.swing.GroupLayout(pnSuplier);
        pnSuplier.setLayout(pnSuplierLayout);
        pnSuplierLayout.setHorizontalGroup(
            pnSuplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSuplierLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnSuplierDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        pnSuplierLayout.setVerticalGroup(
            pnSuplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
            .addComponent(pnSuplierDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tbbSupplier.addTab("Supplier", pnSuplier);

        tblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblItemMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblItem);

        pnItemDetails.setBorder(javax.swing.BorderFactory.createTitledBorder("Item Details"));

        jLabel16.setText("Supplying");

        btnAddNewItem.setText("Add New");
        btnAddNewItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewItemActionPerformed(evt);
            }
        });

        jLabel17.setText("Item Code:");

        jLabel18.setText("Unit");

        jLabel19.setText("Item Name");

        txtCodeItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeItemActionPerformed(evt);
            }
        });

        txtNameItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameItemActionPerformed(evt);
            }
        });

        txtUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnitActionPerformed(evt);
            }
        });

        btnSaveItem.setText("Save");
        btnSaveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveItemActionPerformed(evt);
            }
        });

        btnDeleteItem.setText("Delete");
        btnDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteItemActionPerformed(evt);
            }
        });

        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });

        jLabel24.setText("Price");

        jLabel25.setText("Supplier:");

        CBSupplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnItemDetailsLayout = new javax.swing.GroupLayout(pnItemDetails);
        pnItemDetails.setLayout(pnItemDetailsLayout);
        pnItemDetailsLayout.setHorizontalGroup(
            pnItemDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnItemDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnItemDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddNewItem, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pnItemDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CKsupplying)
                    .addGroup(pnItemDetailsLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnSaveItem, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnDeleteItem, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnItemDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(CBSupplier, javax.swing.GroupLayout.Alignment.LEADING, 0, 212, Short.MAX_VALUE)
                        .addComponent(txtCodeItem, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNameItem, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtUnit, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnItemDetailsLayout.setVerticalGroup(
            pnItemDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnItemDetailsLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(pnItemDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodeItem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnItemDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNameItem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnItemDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(CBSupplier))
                .addGap(7, 7, 7)
                .addGroup(pnItemDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnItemDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(pnItemDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CKsupplying))
                .addGap(51, 51, 51)
                .addGroup(pnItemDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddNewItem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSaveItem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteItem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnItemLayout = new javax.swing.GroupLayout(pnItem);
        pnItem.setLayout(pnItemLayout);
        pnItemLayout.setHorizontalGroup(
            pnItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnItemLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnItemDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 62, Short.MAX_VALUE))
        );
        pnItemLayout.setVerticalGroup(
            pnItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnItemLayout.createSequentialGroup()
                .addGroup(pnItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(pnItemDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tbbSupplier.addTab("Items", pnItem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbbSupplier)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbbSupplier)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodeItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeItemActionPerformed

    private void txtNameItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameItemActionPerformed

    private void txtUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnitActionPerformed

    private void txtSupCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupCodeActionPerformed

    private void txtSupNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupNameActionPerformed

    private void txtAddressSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressSupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressSupActionPerformed

    private void btnDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteItemActionPerformed
        // TODO add your handling code here:
        try {
            int selectedRow = tblItem.getSelectedRow();
            if (selectedRow < 0 || deleteItem == false) {
                JOptionPane.showMessageDialog(this, "Choose the Row to Delete");
                return;
            }
            int r = JOptionPane.showConfirmDialog(this, "Do you want to Delete this Item?");
            if (r == JOptionPane.YES_OPTION) {
                SE140364_Item it = modelItem.getModeItem().getList().get(selectedRow);
                if (modelItem.Delete(it) == SUCCESS) {
                    deleteItem = false;
                    modelItem.getModeItem().getList().remove(it);
                    JOptionPane.showMessageDialog(this, "Deleted");
                    clearInformationItemOnTable();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        tblItem.updateUI();
    }//GEN-LAST:event_btnDeleteItemActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void tblSuppliersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSuppliersMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblSuppliers.getSelectedRow();
        SE140364_Suppliers sup = modelSuppliers.getModelSup().getList().get(selectedRow);
        txtSupCode.setText(sup.getSupCode());
        txtSupCode.setEditable(false);
        txtSupName.setText(sup.getSupName());
        txtAddressSup.setText(sup.getAddress());
        CKcoll.setSelected(sup.isColloborating());
        addNewSup = false;
        deleteSup = true;
    }//GEN-LAST:event_tblSuppliersMouseClicked

    private void btnAddNewSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewSupActionPerformed
        // TODO add your handling code here:
        txtSupCode.setEditable(true);
        clearInformationSupplierOnTable();
        addNewSup = true;
        deleteSup = false;

    }//GEN-LAST:event_btnAddNewSupActionPerformed

    private void btnSaveSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveSupActionPerformed
        // TODO add your handling code here:
        if (!modelSuppliers.validDate(txtSupCode.getText().trim(), txtSupName.getText().trim(), txtAddressSup.getText().trim())) {
            return;
        }
        if (addNewSup) {
            try {
                if (!modelSuppliers.validDateCodeSupplier(txtSupCode.getText().trim())) {
                    JOptionPane.showMessageDialog(this, "DUPLICATE SUPCODE AT " + txtSupCode.getText().trim());
                    return;
                }
                SE140364_Suppliers sup = new SE140364_Suppliers(txtCodeItem.getText().trim(), txtSupName.getText().trim(), txtAddressSup.getText().trim(), CKcoll.isSelected());
                if (modelSuppliers.Insert(sup) == SUCCESS) {
                    modelSuppliers.getModelSup().getList().add(sup);
                    modelSuppliers.getListSuppliersComboBox().add(sup.getSupCode() + " - " + sup.getSupCode());
                }

                addNewSup = false;
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            try {
                int selectedRow = tblSuppliers.getSelectedRow();
                if (selectedRow < 0) {
                    JOptionPane.showMessageDialog(this, "Choose Row to Exit");
                    return;
                }

                SE140364_Suppliers supNew = new SE140364_Suppliers(txtSupCode.getText().trim(), txtSupName.getText().trim(), txtAddressSup.getText().trim(), CKcoll.isSelected());
                SE140364_Suppliers supOld = modelSuppliers.getModelSup().getList().get(selectedRow);

                if (modelSuppliers.Save(supNew) == SUCCESS) {
                    modelSuppliers.getListSuppliersComboBox().remove(supOld.getSupCode() + " - " + supOld.getSupName());
                    supOld.setSupName(supNew.getSupName());
                    supOld.setAddress(supNew.getAddress());
                    supOld.setColloborating(supNew.isColloborating());
                    modelSuppliers.getListSuppliersComboBox().add(supNew.getSupCode() + " - " + supNew.getSupName());

                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        modelItem.getModeItem().loadSuppliersComboBox();
        CBSupplier.setModel(new DefaultComboBoxModel<>(modelSuppliers.getListSuppliersComboBox()));
        tblSuppliers.updateUI();
    }//GEN-LAST:event_btnSaveSupActionPerformed

    private void btnDeleteSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSupActionPerformed
        // TODO add your handling code here:
        try {
            int selectedRow = tblSuppliers.getSelectedRow();
            if (selectedRow < 0 || deleteSup == false) {
                JOptionPane.showMessageDialog(this, "Choose the Row to Delete");
                return;
            }
            int r = JOptionPane.showConfirmDialog(this, "Do you want to Delete this Supplier?");
            if (r == JOptionPane.YES_OPTION) {
                SE140364_Suppliers sup = modelSuppliers.getModelSup().getList().get(selectedRow);
                if (!modelItem.checkConstraintSupCode(sup.getSupCode())) {
                    JOptionPane.showMessageDialog(this, "Still Items is manager by this Supplier");
                    return;
                }
                if (modelSuppliers.Delete(sup) == SUCCESS) {
                    deleteSup = false;
                    modelSuppliers.getModelSup().getList().remove(sup);
                    modelSuppliers.getListSuppliersComboBox().remove(sup.getSupCode() + " - " + sup.getSupName());
                    JOptionPane.showMessageDialog(this, "Deleted");
                    CBSupplier.setModel(new DefaultComboBoxModel<>(modelSuppliers.getListSuppliersComboBox()));
                    clearInformationSupplierOnTable();
                    modelItem.getModeItem().loadSuppliersComboBox();
                    tblSuppliers.updateUI();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDeleteSupActionPerformed

    private void btnAddNewItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewItemActionPerformed
        // TODO add your handling code here:
        txtCodeItem.setEditable(true);
        clearInformationItemOnTable();
        addNewItem = true;
        deleteItem = false;
    }//GEN-LAST:event_btnAddNewItemActionPerformed

    private void btnSaveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveItemActionPerformed
        // TODO add your handling code here:
        if (!modelItem.validDate(txtCodeItem.getText().trim(), txtNameItem.getText().trim(), txtUnit.getText().trim(), txtPrice.getText().trim(), CBSupplier.getSelectedItem())) {
            return;
        }
        if (addNewItem) {
            try {
                if (!modelItem.validDateCodeItem(txtCodeItem.getText().trim())) {
                    JOptionPane.showMessageDialog(this, "DUPLICATED ITEMCODE at " + txtCodeItem.getText().trim());
                    return;
                }
                SE140364_Item it = new SE140364_Item(txtCodeItem.getText().toUpperCase().trim(), txtNameItem.getText().trim(), txtUnit.getText().trim(),
                        Float.parseFloat(txtPrice.getText().trim()), CKsupplying.isSelected(), modelItem.loadSupCodeIntoItems(CBSupplier.getSelectedItem().toString()));
                if (modelItem.Insert(it) == SUCCESS) {
                    modelItem.getModeItem().getList().add(it);
                }
                addNewItem = false;
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            try {
                int selectedRow = tblItem.getSelectedRow();
                if (selectedRow < 0) {
                    JOptionPane.showMessageDialog(this, "Please Choose Row to Edit");
                }

                SE140364_Item itOld = modelItem.getModeItem().getList().get(selectedRow);
                SE140364_Item itNew = new SE140364_Item(txtCodeItem.getText().trim().toUpperCase(), txtNameItem.getText().trim(), txtUnit.getText().trim(), Float.parseFloat(txtPrice.getText().trim()), CKsupplying.isSelected(), modelItem.loadSupCodeIntoItems(CBSupplier.getSelectedItem().toString()));
                if (modelItem.Save(itNew) == SUCCESS) {
                    itOld.setItemName(itNew.getItemName());
                    itOld.setPrice(itNew.getPrice());
                    itOld.setUnit(itNew.getUnit());
                    itOld.setSupCode(itNew.getSupCode());
                    itOld.setSupplying(itNew.isSupplying());

                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        tblItem.updateUI();
    }//GEN-LAST:event_btnSaveItemActionPerformed

    private void tblItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItemMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblItem.getSelectedRow();
        SE140364_Item it = modelItem.getModeItem().getList().get(selectedRow);
        txtCodeItem.setText(it.getItemCode());
        txtCodeItem.setEditable(false);
        txtNameItem.setText(it.getItemName());
        txtUnit.setText(it.getUnit());
        txtPrice.setText(it.getPrice() + "");
        CKsupplying.setSelected(it.isSupplying());
        CBSupplier.setSelectedItem(it.getSupCode() + " - " + modelSuppliers.getSupNameComboBox(it.getSupCode()));
        addNewItem = false;
        deleteItem = true;
    }//GEN-LAST:event_tblItemMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SE140364_ManagementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SE140364_ManagementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SE140364_ManagementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SE140364_ManagementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new SE140364_ManagementUI().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(SE140364_ManagementUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBSupplier;
    private javax.swing.JCheckBox CKcoll;
    private javax.swing.JCheckBox CKsupplying;
    private javax.swing.JButton btnAddNewItem;
    private javax.swing.JButton btnAddNewSup;
    private javax.swing.JButton btnDeleteItem;
    private javax.swing.JButton btnDeleteSup;
    private javax.swing.JButton btnSaveItem;
    private javax.swing.JButton btnSaveSup;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel pnItem;
    private javax.swing.JPanel pnItemDetails;
    private javax.swing.JPanel pnSuplier;
    private javax.swing.JPanel pnSuplierDetails;
    private javax.swing.JTabbedPane tbbSupplier;
    private javax.swing.JTable tblItem;
    private javax.swing.JTable tblSuppliers;
    private javax.swing.JTextField txtAddressSup;
    private javax.swing.JTextField txtCodeItem;
    private javax.swing.JTextField txtNameItem;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSupCode;
    private javax.swing.JTextField txtSupName;
    private javax.swing.JTextField txtUnit;
    // End of variables declaration//GEN-END:variables
}
